[build]
  functions = "functions/"

[[redirects]]
  from = "/products/*"
  to = "/products/item"
  status = 200
  query = {item = ":id"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200